name: InventoryControlPlugin
version: '${version}'

main: net.dvmn2.inventorycontrolplugin.InventoryControlPlugin
api-version: '1.21'
load: POSTWORLD

authors: [ DVMN2 ]

permissions:
  inventorycontrol.admin:
    description: Доступ к командам /inventorycontrol set|get|reset
    default: op